---
title: "Lecture Title"
author: "Thomas Manke"
date:  last-updated
categories:
  - content
---

## Description

## Objectives

Upon successful completion of this course, students will understand ...

They will be proficient in ...

## Content

-   01

-   02

## Prerequisites

-   01
-   02

## Format

This course will be *interactive* (need laptop) and *collaborative* (work in small teams). It will comprise the following blocks:

-   *Lectures:* will provide an introduction and overview of Data Science concepts and R functionality

-   *Homeworks/Projects*: lecture-based tasks, to be solved and submitted individually.

-   *Tutorials*: During the tutorials the teams will present their solutions and lecture material will be reviewed as necessary.

-   Exams:

## Times and Locations

| Format    | Times | Location | Instructor |
|-----------|-------|----------|------------|
| Lectures  |       |          | T. Manke   |
| Tutorials |       |          | T. Manke   |
| Exam      |       |          |            |

## Evaluation

-   Lectures: Presence (15%+15% rule)

-   Tutorials (10 P): Homework Assignments & Presentations

-   Data Analysis Project (20 P): Presentation and submission of a reproducible data analysis project in an executable markdown format.

## Materials and References

-   Ref1: Link1
-   Ref2: Link2