project:
  type: website
  output-dir: docs
  
website:
  title: "Lecture Title"
#  favicon: images/Manke_2019.11.17_small.JPG

  navbar:
    left: 
      - text: "Overview"
        icon: menu-up
        href: general/Overview.qmd
        
      - text: "Lectures"
        icon: book
        menu: 
          - text: "Topic 00"
            href: lectures/topic_00/index.qmd
          - text: "Topic 01"
            href: lectures/topic_01/index.qmd  
      - text: "Homework"
        icon: list-task
        href: homework/index.qmd
      - text: "Projects"
        icon: bricks
        href: projects/index.qmd


    right:
      - general/about.qmd
      - icon: github
        href: https://github.com/thomasmanke/

  page-footer: 
    left: |
      Made with Quatro   
    center: 
      - general/about.qmd
    right:
      - icon: github
        href: https://github.com/thomasmanke/blog
    background: "grey"
    
#  sidebar:
#      - id: get-started
#        title: "Get Started"
#        style: "floating"
  
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    code-link: false
    code-fold: show
#    code-tools: true
    highlight-style: github

execute:
  freeze: auto
  
editor: visual

